language: node_js
node_js:
- 10.4.1
cache:
  directories:
  - node_modules
install:
- npm install
before_script: 
script:
  - npm run test
after_script:
- cd ./dist
- git init
- git config user.name "${U_NAME}"
- git config user.email "${U_EMAIL}"
- git add .
- git commit -m "Update tools"
- git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:${P_BRANCH}
branches:
  only:
  - master
env:
  global: 
before_install:
- openssl aes-256-cbc -K $encrypted_91a6ab91630f_key -iv $encrypted_91a6ab91630f_iv
  -in rongcuifang_rsa.enc -out ~/.ssh/rongcuifang_rsa -d
  - chmod 600 ~/.ssh/rongcuifang_rsa
 # - echo -e "Host 102.201.64.94\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
